# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='cache/images/')),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('key', models.CharField(max_length=2048, unique=True)),
            ],
        ),
    ]
