# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppedimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cropped-images/images/'),
        ),
    ]
